# Generated by Django 2.2.2 on 2019-06-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_telephone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название сайта'),
        ),
    ]
